import json
from pathlib import Path

from flask import Flask, render_template


BASE_DIR = Path(__file__).resolve().parent
ML_RESULTS_PATH = BASE_DIR / "FLCP_ML" / "ml_results.json"
DL_RESULTS_PATH = BASE_DIR / "FLCP_DL" / "dl_results.json"
QML_RESULTS_PATH = BASE_DIR / "FLCP_QML" / "model_results.json"

app = Flask(__name__)


def load_json(path):
    path = Path(path)
    if not path.exists():
        return None

    with path.open("r", encoding="utf-8") as result_file:
        return json.load(result_file)


def to_percentage(value):
    if value is None:
        return None
    return round(float(value) * 100, 2)


def build_dashboard_context():
    ml_results = load_json(ML_RESULTS_PATH)
    dl_results = load_json(DL_RESULTS_PATH)
    qml_results = load_json(QML_RESULTS_PATH)

    ml_section = {
        "available": ml_results is not None,
        "cards": [
            {"title": "KNN", "accuracy": None},
            {"title": "Decision Tree", "accuracy": None},
            {"title": "Random Forest", "accuracy": None},
        ],
        "best_model": None,
        "best_accuracy": None,
        "message": "Run the ML training stage to generate the comparison metrics.",
    }

    if ml_results:
        ml_section.update(
            {
                "cards": [
                    {"title": "KNN", "accuracy": to_percentage(ml_results.get("knn_accuracy"))},
                    {
                        "title": "Decision Tree",
                        "accuracy": to_percentage(ml_results.get("decision_tree_accuracy")),
                    },
                    {
                        "title": "Random Forest",
                        "accuracy": to_percentage(ml_results.get("random_forest_accuracy")),
                    },
                ],
                "best_model": ml_results.get("best_model"),
                "best_accuracy": to_percentage(ml_results.get("best_accuracy")),
                "message": None,
            }
        )

    dl_accuracy = None
    if dl_results:
        dl_accuracy = to_percentage(dl_results.get("accuracy"))

    qml_accuracy = None
    qml_classical_accuracy = None
    if qml_results:
        qml_accuracy = to_percentage(qml_results.get("quantum_accuracy"))
        qml_classical_accuracy = to_percentage(qml_results.get("classical_accuracy"))

    leaderboard = []
    if ml_section["best_accuracy"] is not None:
        leaderboard.append(("ML - " + ml_section["best_model"], ml_section["best_accuracy"]))
    if dl_accuracy is not None:
        leaderboard.append(("DNN", dl_accuracy))
    if qml_accuracy is not None:
        leaderboard.append(("QML", qml_accuracy))

    if leaderboard:
        best_name, best_score = max(leaderboard, key=lambda item: item[1])
        conclusion = (
            f"The best-performing approach in the current demo output is {best_name} "
            f"with an accuracy of {best_score:.2f}%. This page summarizes the pipeline "
            "outputs generated by DVC, while MLflow keeps the detailed experiment history."
        )
    else:
        conclusion = (
            "No comparison metrics are available yet. Run the training scripts or `dvc repro` "
            "to generate the ML, DNN, and QML outputs, then refresh this page."
        )

    return {
        "ml_section": ml_section,
        "dl_section": {
            "available": dl_accuracy is not None,
            "accuracy": dl_accuracy,
            "message": "Run the DNN training stage to generate the deep learning accuracy.",
        },
        "qml_section": {
            "available": qml_accuracy is not None,
            "accuracy": qml_accuracy,
            "classical_accuracy": qml_classical_accuracy,
            "message": "Run the QML training stage to generate the quantum comparison metrics.",
        },
        "conclusion": conclusion,
    }


@app.route("/")
def dashboard():
    return render_template("index.html", **build_dashboard_context())


if __name__ == "__main__":
    app.run(debug=True, port=5000)
