stages:
  ml:
    cmd: python FLCP_ML/train_ml.py
    deps:
      - FLCP_ML/train_ml.py
      - FLCP_ML/ML/knn.py
      - FLCP_ML/ML/decision_tree.py
      - FLCP_ML/ML/random_forest.py
      - DATA/lungcancer_clean.csv
    outs:
      - FLCP_ML/ml_results.json

  dl:
    cmd: python FLCP_DL/train_dl.py
    deps:
      - FLCP_DL/train_dl.py
      - DATA/lungcancer_clean.csv
    outs:
      - FLCP_DL/dl_results.json

  qml:
    cmd: python FLCP_QML/qml_model.py
    deps:
      - FLCP_QML/qml_model.py
      - FLCP_QML/generate_report.py
      - DATA/lungcancer_clean.csv
    outs:
      - FLCP_QML/model_results.json
